# -- Default spring configuration

spring:
  application:
    name: post

# -- Eureka client
#  defaultZone = eureka server ip:port ??? ????.
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8888/eureka/}
server:
  port: 8882